# Generated by Django 4.2.5 on 2023-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_student_delete_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
