# Generated by Django 4.2.5 on 2023-10-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_beca_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='id_estudiante',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beca',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
