# Generated by Django 4.2.5 on 2023-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_alter_beca_id_estudiante_alter_beca_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='id_estudiante',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
