# Generated by Django 4.2.5 on 2023-10-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='peso',
        ),
    ]
