# Generated by Django 4.2.5 on 2023-10-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_remove_archivo_archivo_remove_archivo_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAcademicActvitiesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
                ('activity_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('semester', models.CharField(max_length=6)),
            ],
        ),
    ]
