# Generated by Django 4.2.5 on 2023-10-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_nonacademicactvitiesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CREAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('monitor_name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
    ]
