# Generated by Django 4.2.5 on 2023-10-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_creareport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=1000)),
                ('type', models.CharField(choices=[('Natural', 'Natural'), ('Legal', 'Legal')], max_length=7)),
                ('description', models.CharField(max_length=1000)),
                ('previous_colaborations', models.CharField(max_length=1000)),
            ],
        ),
    ]
