# Generated by Django 4.2.5 on 2023-11-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='student',
        ),
        migrations.AddField(
            model_name='documento',
            name='student_code',
            field=models.CharField(default='', max_length=9),
        ),
    ]
