# Generated by Django 4.2.5 on 2023-11-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_donor'),
        ('crud', '0020_remove_document_title'),
    ]

    operations = [
    ]
