# Generated by Django 4.2.5 on 2023-11-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0021_merge_0016_donor_0020_remove_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=200)),
                ('student_code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
