# Generated by Django 4.2.5 on 2023-11-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_alerta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='nombre',
        ),
    ]
