# Generated by Django 4.2.5 on 2023-11-21 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0023_remove_alerta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
