# Generated by Django 4.2.5 on 2023-11-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0024_alter_alerta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='donor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.donor'),
        ),
    ]
