# Generated by Django 4.2.5 on 2023-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0030_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_rol',
            field=models.CharField(choices=[('Filantropía', 'Filantropía'), ('Bienestar Universitario', 'Bienestar Universitario')], max_length=100),
        ),
    ]
