# Generated by Django 4.2.5 on 2023-11-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0031_alter_user_user_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_rol',
            new_name='user_type',
        ),
    ]
