# Generated by Django 4.2.5 on 2023-11-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0032_rename_user_rol_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Bienestar Universitario', 'Bienestar Universitario'), ('Filantropía', 'Filantropía')], max_length=100),
        ),
    ]
