# Generated by Django 4.2.5 on 2023-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0036_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Filantropía', 'Filantropía'), ('Bienestar Universitario', 'Bienestar Universitario')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=1000, unique=True),
        ),
    ]
