# Generated by Django 4.2.5 on 2023-11-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0039_alter_user_groups_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Filantropía', 'Filantropía'), ('CREA', 'CREA'), ('Apoyo Financiero', 'Apoyo Financiero'), ('Director de Programa', 'Director de Programa'), ('Registro Académico', 'Registro Académico'), ('Bienestar Universitario', 'Bienestar Universitario')], max_length=100, null=True),
        ),
    ]
